### PR TITLE
Fix a build error for rbtree dependency using Ruby 3.2.0dev

### LINKED ISSUE #11: Can't install on ruby-head because rbtree dependency uses rb_cData
```
$ gem install sorted_set
[...]
rbtree.c: In function ‘Init_rbtree’:
rbtree.c:1900:50: error: ‘rb_cData’ undeclared (first use in this function)
 1900 |     MultiRBTree = rb_define_class("MultiRBTree", rb_cData);
      |                                                  ^~~~~~~~
[...]
```

probably caused by https://github.com/ruby/ruby/commit/7c738ce5e649b82bdc1305d5c347e81886ee759a

### PR DESCRIPTION
**Pull request by koic**
Fixes #11.

The original rbtree gem didn't seem to be maintained anymore.
https://github.com/skade/rbtree

And a forked gem called rbtree3 solves the #11 error.

- https://rubygems.org/gems/rbtree3
- https://github.com/kyrylo/rbtree3

The PR that is resolving the build error:
https://github.com/kyrylo/rbtree3/pull/14

I'm not sure about gem replacement is the best, but the error will be resolved anyway.

### CODE REVIEW

**Comment by koic** [comment]
Oops, I overlooked https://github.com/rails/rails/pull/44152 conversations. I will wait for the next new rbtree release and close this PR.

**Comment by koic** [comment]
I'm going to close this PR because I heard from @yahonda on an online meetup that the Ruby core team is working on the rbtree issue. Thank you.
