### ISSUE TITLE
Can't install on ruby-head because rbtree dependency uses rb_cData

### ISSUE THREAD

**Issue by jaynetics** [knu/sorted_set#11]
```
$ gem install sorted_set
[...]
rbtree.c: In function ‘Init_rbtree’:
rbtree.c:1900:50: error: ‘rb_cData’ undeclared (first use in this function)
 1900 |     MultiRBTree = rb_define_class("MultiRBTree", rb_cData);
      |                                                  ^~~~~~~~
[...]
```

probably caused by https://github.com/ruby/ruby/commit/7c738ce5e649b82bdc1305d5c347e81886ee759a

**Comment by yahonda** [comment]
I also wanted this issue addressed because Ruby on Rails CI also needs that as it reported https://github.com/rails/rails/issues/44101

I think this error needs to be addressed at `rbtree` gem but I have not found a public GitHub repository for `rbtree` . Then let me inform this issue here.

**Comment by koic** [comment]
JFYI, https://rubygems.org/gems/rbtree/versions/0.4.5 solved this issue.

**Comment by yahonda** [comment]
Confirmed that sorted_set can be installed as follows.
 
```
$ ruby -v
ruby 3.2.0dev (2022-02-06T15:44:40Z master a07fa198a6) [x86_64-linux]
$ gem -v
3.4.0.dev
$ gem install sorted_set
Fetching rbtree-0.4.5.gem
Building native extensions. This could take a while...
Successfully installed rbtree-0.4.5
Successfully installed sorted_set-1.0.3
Parsing documentation for rbtree-0.4.5
Installing ri documentation for rbtree-0.4.5
Parsing documentation for sorted_set-1.0.3
Installing ri documentation for sorted_set-1.0.3
Done installing documentation for rbtree, sorted_set after 0 seconds
2 gems installed
$
```

**Comment by jaynetics** [comment]
@koic @yahonda 

thanks for letting me know! i'll close this issue then.

do you know what the reasoning is not to use the better-maintained, publicly visible community fork of rbtree, rbtree3?

either way, it would be nice to set up a regular build for `sorted_set` that also checks for deprecations, to prevent it from breaking unexpectedly again.

some of the other open issues could also be fixed fairly easily.

i've sent @knu a mail offering my support to maintain it, but haven't heard back from him.
